### ISSUE TITLE
Bug in Storage when App Restarts

### ISSUE THREAD

**Issue by agnesnatasya** [AY1920S2-CS2103-W15-2/main#197]
When the app is closed, the data of the interview of all interviewees that has been interviewed was gone and the interviewee is stated as "has not been interviewed". This is incorrect as the app need to store the correct state of all the data of the app after closing and after reopening.

**Comment by CornCobs** [comment]
This is strange, our loading method has not really changed, it was just refactored to a different place (not when the app starts)

**Comment by CornCobs** [comment]
Ok after some digging around, the interviewee.json file still shows that the interviewees "transcript" is set to false even after interviewing. This is probably because we do not save the interviewee list after modifying the interviewee's transcript.

This was not a problem before #190 since we saved all components (except transcript) after each command. The stopgap measure actually hid a bug in our implementation!
